#! /usr/bin/env python

import log

from shell import Shell


def main():

        log.write(mes="Txtsh started.")

        sh = Shell()
        sh.run()

        return


if __name__ == '__main__':
        main()
